[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
indicatif = "0.17.11"
rand = "0.9.0"
rayon = "1.10.0"
riddance = "0.3.0"
